[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/', '@solmate/=lib/solmate/src/tokens']
solc-version = '0.8.10'

# See more config options https://github.com/gakonst/foundry/tree/master/config
